<?php

$usuarios = [
    [
        'id' => 1,
        'name' => 'João Silva',
        'gender' => 'men',
        'birthdate' => '25-01-1995',
        'mail' => 'admin@user.com',
        'phone' => '19912345678',
        'isActive' => 1,
        'address' => 'Rua A, 123',
        'avatar' => 'avatar1.jpg',
        'job' => 'Desenvolvedor',
        'jobType' => 1,
        'qtdeTask' => '6',
        'qtdeAssets' => '3',
        'qtdeSubAssets' => '54',
    ],
    [
        'id' => 2,
        'name' => 'Maria Oliveira',
        'gender' => 'women',
        'birthdate' => '25-01-1995',
        'mail' => 'admin@user.com',
        'phone' => '19912345678',
        'isActive' => 0,
        'address' => 'Avenida B, 456',
        'avatar' => 'avatar2.jpg',
        'job' => 'Designer',
        'jobType' => 2,
        'qtdeTask' => '4',
        'qtdeAssets' => '45',
        'qtdeSubAssets' => '43',
    ],
    [
        'id' => 3,
        'name' => 'Pedro Souza',
        'gender' => 'men',
        'birthdate' => '25-01-1995',
        'mail' => 'admin@user.com',
        'phone' => '19912345678',
        'isActive' => 0,
        'address' => 'Rua A, 123',
        'avatar' => 'avatar1.jpg',
        'job' => 'Desenvolvedor',
        'jobType' => 1,
        'qtdeTask' => '43',
        'qtdeAssets' => '12',
        'qtdeSubAssets' => '1',
    ],
    [
        'id' => 4,
        'name' => 'Julio Cezar',
        'gender' => 'men',
        'birthdate' => '25-01-1995',
        'mail' => 'admin@user.com',
        'phone' => '19912345678',
        'isActive' => 1,
        'address' => 'Rua A, 123',
        'avatar' => 'avatar1.jpg',
        'job' => 'Designer',
        'jobType' => 2,
        'qtdeTask' => '3',
        'qtdeAssets' => '1',
        'qtdeSubAssets' => '1',
    ],
    [
        'id' => 5,
        'name' => 'Pedro Alvarez dos Santos',
        'gender' => 'men',
        'birthdate' => '25-01-1995',
        'mail' => 'admin@user.com',
        'phone' => '19912345678',
        'isActive' => 1,
        'address' => 'Rua A, 123',
        'avatar' => 'avatar1.jpg',
        'job' => 'Desenvolvedor',
        'jobType' => 1,
        'qtdeTask' => '45',
        'qtdeAssets' => '3',
        'qtdeSubAssets' => '7',
    ],
    [
        'id' => 6,
        'name' => 'Clara',
        'gender' => 'women',
        'birthdate' => '25-01-1995',
        'mail' => 'admin@user.com',
        'phone' => '19912345678',
        'isActive' => 0,
        'address' => 'Rua A, 123',
        'avatar' => 'avatar1.jpg',
        'job' => 'Desginer',
        'jobType' => 2,
        'qtdeTask' => '6',
        'qtdeAssets' => '5',
        'qtdeSubAssets' => '3',
    ],
];
